#include "stops.h"

// Route 1 (38 stops)
const char *const stops_line_1[] = {
    "Van Cortlandt Park-242 St",
    "238 St",
    "231 St",
    "Marble Hill-225 St",
    "215 St",
    "207 St",
    "Dyckman St",
    "191 St",
    "181 St",
    "168 St-Washington Hts",
    "157 St",
    "145 St",
    "137 St-City College",
    "125 St",
    "116 St-Columbia University",
    "Cathedral Pkwy (110 St)",
    "103 St",
    "96 St",
    "86 St",
    "79 St",
    "72 St",
    "66 St-Lincoln Center",
    "59 St-Columbus Circle",
    "50 St",
    "Times Sq-42 St",
    "34 St-Penn Station",
    "28 St",
    "23 St",
    "18 St",
    "14 St",
    "Christopher St-Stonewall",
    "Houston St",
    "Canal St",
    "Franklin St",
    "Chambers St",
    "WTC Cortlandt",
    "Rector St",
    "South Ferry",
};
const uint8_t stops_line_1_count = 38;

// Route 2 (61 stops)
const char *const stops_line_2[] = {
    "Wakefield-241 St",
    "Nereid Av",
    "233 St",
    "225 St",
    "219 St",
    "Gun Hill Rd",
    "Burke Av",
    "Allerton Av",
    "Pelham Pkwy",
    "Bronx Park East",
    "E 180 St",
    "West Farms Sq-E Tremont Av",
    "174 St",
    "Freeman St",
    "Simpson St",
    "Intervale Av",
    "Prospect Av",
    "Jackson Av",
    "3 Av-149 St",
    "149 St-Grand Concourse",
    "135 St",
    "125 St",
    "116 St",
    "110 St-Malcolm X Plaza",
    "96 St",
    "86 St",
    "79 St",
    "72 St",
    "66 St-Lincoln Center",
    "59 St-Columbus Circle",
    "50 St",
    "Times Sq-42 St",
    "34 St-Penn Station",
    "28 St",
    "23 St",
    "18 St",
    "14 St",
    "Christopher St-Stonewall",
    "Houston St",
    "Canal St",
    "Franklin St",
    "Chambers St",
    "Park Place",
    "Fulton St",
    "Wall St",
    "Clark St",
    "Borough Hall",
    "Hoyt St",
    "Nevins St",
    "Atlantic Av-Barclays Ctr",
    "Bergen St",
    "Grand Army Plaza",
    "Eastern Pkwy-Brooklyn Museum",
    "Franklin Av-Medgar Evers College",
    "President St-Medgar Evers College",
    "Sterling St",
    "Winthrop St",
    "Church Av",
    "Beverly Rd",
    "Newkirk Av-Little Haiti",
    "Flatbush Av-Brooklyn College",
};
const uint8_t stops_line_2_count = 61;

// Route 3 (34 stops)
const char *const stops_line_3[] = {
    "Harlem-148 St",
    "145 St",
    "135 St",
    "125 St",
    "116 St",
    "110 St-Malcolm X Plaza",
    "96 St",
    "72 St",
    "Times Sq-42 St",
    "34 St-Penn Station",
    "14 St",
    "Chambers St",
    "Park Place",
    "Fulton St",
    "Wall St",
    "Clark St",
    "Borough Hall",
    "Hoyt St",
    "Nevins St",
    "Atlantic Av-Barclays Ctr",
    "Bergen St",
    "Grand Army Plaza",
    "Eastern Pkwy-Brooklyn Museum",
    "Franklin Av-Medgar Evers College",
    "Nostrand Av",
    "Kingston Av",
    "Crown Hts-Utica Av",
    "Sutter Av-Rutland Rd",
    "Saratoga Av",
    "Rockaway Av",
    "Junius St",
    "Pennsylvania Av",
    "Van Siclen Av",
    "New Lots Av",
};
const uint8_t stops_line_3_count = 34;

// Route 4 (54 stops)
const char *const stops_line_4[] = {
    "Woodlawn",
    "Mosholu Pkwy",
    "Bedford Park Blvd-Lehman College",
    "Kingsbridge Rd",
    "Fordham Rd",
    "183 St",
    "Burnside Av",
    "176 St",
    "Mt Eden Av",
    "170 St",
    "167 St",
    "161 St-Yankee Stadium",
    "149 St-Grand Concourse",
    "138 St-Grand Concourse",
    "125 St",
    "116 St",
    "110 St",
    "103 St",
    "96 St",
    "86 St",
    "77 St",
    "68 St-Hunter College",
    "59 St",
    "51 St",
    "Grand Central-42 St",
    "33 St",
    "28 St",
    "23 St-Baruch College",
    "14 St-Union Sq",
    "Astor Pl",
    "Bleecker St",
    "Spring St",
    "Canal St",
    "Brooklyn Bridge-City Hall",
    "Fulton St",
    "Wall St",
    "Bowling Green",
    "Borough Hall",
    "Nevins St",
    "Atlantic Av-Barclays Ctr",
    "Bergen St",
    "Grand Army Plaza",
    "Eastern Pkwy-Brooklyn Museum",
    "Franklin Av-Medgar Evers College",
    "Nostrand Av",
    "Kingston Av",
    "Crown Hts-Utica Av",
    "Sutter Av-Rutland Rd",
    "Saratoga Av",
    "Rockaway Av",
    "Junius St",
    "Pennsylvania Av",
    "Van Siclen Av",
    "New Lots Av",
};
const uint8_t stops_line_4_count = 54;

// Route 5 (39 stops)
const char *const stops_line_5[] = {
    "New Lots Av",
    "Van Siclen Av",
    "Pennsylvania Av",
    "Junius St",
    "Rockaway Av",
    "Saratoga Av",
    "Sutter Av-Rutland Rd",
    "Crown Hts-Utica Av",
    "Kingston Av",
    "Nostrand Av",
    "Franklin Av-Medgar Evers College",
    "Atlantic Av-Barclays Ctr",
    "Nevins St",
    "Borough Hall",
    "Bowling Green",
    "Wall St",
    "Fulton St",
    "Brooklyn Bridge-City Hall",
    "14 St-Union Sq",
    "Grand Central-42 St",
    "59 St",
    "86 St",
    "125 St",
    "138 St-Grand Concourse",
    "149 St-Grand Concourse",
    "3 Av-149 St",
    "Jackson Av",
    "Prospect Av",
    "Intervale Av",
    "Simpson St",
    "Freeman St",
    "174 St",
    "West Farms Sq-E Tremont Av",
    "E 180 St",
    "Morris Park",
    "Pelham Pkwy",
    "Gun Hill Rd",
    "Baychester Av",
    "Eastchester-Dyre Av",
};
const uint8_t stops_line_5_count = 39;

// Route 6 (38 stops)
const char *const stops_line_6[] = {
    "Pelham Bay Park",
    "Buhre Av",
    "Middletown Rd",
    "Westchester Sq-E Tremont Av",
    "Zerega Av",
    "Castle Hill Av",
    "Parkchester",
    "St Lawrence Av",
    "Morrison Av-Soundview",
    "Elder Av",
    "Whitlock Av",
    "Hunts Point Av",
    "Longwood Av",
    "E 149 St",
    "E 143 St-St Mary's St",
    "Cypress Av",
    "Brook Av",
    "3 Av-138 St",
    "125 St",
    "116 St",
    "110 St",
    "103 St",
    "96 St",
    "86 St",
    "77 St",
    "68 St-Hunter College",
    "59 St",
    "51 St",
    "Grand Central-42 St",
    "33 St",
    "28 St",
    "23 St-Baruch College",
    "14 St-Union Sq",
    "Astor Pl",
    "Bleecker St",
    "Spring St",
    "Canal St",
    "Brooklyn Bridge-City Hall",
};
const uint8_t stops_line_6_count = 38;

// Route 6X (29 stops)
const char *const stops_line_6X[] = {
    "Pelham Bay Park",
    "Buhre Av",
    "Middletown Rd",
    "Westchester Sq-E Tremont Av",
    "Zerega Av",
    "Castle Hill Av",
    "Parkchester",
    "Hunts Point Av",
    "3 Av-138 St",
    "125 St",
    "116 St",
    "110 St",
    "103 St",
    "96 St",
    "86 St",
    "77 St",
    "68 St-Hunter College",
    "59 St",
    "51 St",
    "Grand Central-42 St",
    "33 St",
    "28 St",
    "23 St-Baruch College",
    "14 St-Union Sq",
    "Astor Pl",
    "Bleecker St",
    "Spring St",
    "Canal St",
    "Brooklyn Bridge-City Hall",
};
const uint8_t stops_line_6X_count = 29;

// Route 7 (22 stops)
const char *const stops_line_7[] = {
    "34 St-Hudson Yards",
    "Times Sq-42 St",
    "5 Av",
    "Grand Central-42 St",
    "Vernon Blvd-Jackson Av",
    "Hunters Point Av",
    "Court Sq",
    "Queensboro Plaza",
    "33 St-Rawson St",
    "40 St-Lowery St",
    "46 St-Bliss St",
    "52 St",
    "61 St-Woodside",
    "69 St",
    "74 St-Broadway",
    "82 St-Jackson Hts",
    "90 St-Elmhurst Av",
    "Junction Blvd",
    "103 St-Corona Plaza",
    "111 St",
    "Mets-Willets Point",
    "Flushing-Main St",
};
const uint8_t stops_line_7_count = 22;

// Route 7X (18 stops)
const char *const stops_line_7X[] = {
    "34 St-Hudson Yards",
    "Times Sq-42 St",
    "5 Av",
    "Grand Central-42 St",
    "Vernon Blvd-Jackson Av",
    "Hunters Point Av",
    "Court Sq",
    "Queensboro Plaza",
    "33 St-Rawson St",
    "40 St-Lowery St",
    "46 St-Bliss St",
    "52 St",
    "61 St-Woodside",
    "69 St",
    "74 St-Broadway",
    "Junction Blvd",
    "Mets-Willets Point",
    "Flushing-Main St",
};
const uint8_t stops_line_7X_count = 18;

// Route A (59 stops)
const char *const stops_A[] = {
    "Far Rockaway-Mott Av",
    "Beach 25 St",
    "Beach 36 St",
    "Beach 44 St",
    "Beach 60 St",
    "Beach 67 St",
    "Broad Channel",
    "Howard Beach-JFK Airport",
    "Aqueduct-N Conduit Av",
    "Aqueduct Racetrack",
    "Rockaway Blvd",
    "88 St",
    "80 St",
    "Grant Av",
    "Euclid Av",
    "Shepherd Av",
    "Van Siclen Av",
    "Liberty Av",
    "Broadway Junction",
    "Rockaway Av",
    "Ralph Av",
    "Utica Av",
    "Kingston-Throop Avs",
    "Nostrand Av",
    "Franklin Av",
    "Clinton-Washington Avs",
    "Lafayette Av",
    "Hoyt-Schermerhorn Sts",
    "Jay St-MetroTech",
    "High St",
    "Fulton St",
    "Chambers St",
    "Canal St",
    "Spring St",
    "W 4 St-Wash Sq",
    "14 St",
    "23 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "50 St",
    "59 St-Columbus Circle",
    "72 St",
    "81 St-Museum of Natural History",
    "86 St",
    "96 St",
    "103 St",
    "Cathedral Pkwy (110 St)",
    "116 St",
    "125 St",
    "135 St",
    "145 St",
    "155 St",
    "163 St-Amsterdam Av",
    "168 St",
    "175 St",
    "181 St",
    "190 St",
    "Dyckman St",
    "Inwood-207 St",
};
const uint8_t stops_A_count = 59;

// Route B (37 stops)
const char *const stops_B[] = {
    "Bedford Park Blvd",
    "Kingsbridge Rd",
    "Fordham Rd",
    "182-183 Sts",
    "Tremont Av",
    "174-175 Sts",
    "170 St",
    "167 St",
    "161 St-Yankee Stadium",
    "155 St",
    "145 St",
    "135 St",
    "125 St",
    "116 St",
    "Cathedral Pkwy (110 St)",
    "103 St",
    "96 St",
    "86 St",
    "81 St-Museum of Natural History",
    "72 St",
    "59 St-Columbus Circle",
    "7 Av",
    "47-50 Sts-Rockefeller Ctr",
    "42 St-Bryant Pk",
    "34 St-Herald Sq",
    "W 4 St-Wash Sq",
    "Broadway-Lafayette St",
    "Grand St",
    "DeKalb Av",
    "Atlantic Av-Barclays Ctr",
    "7 Av",
    "Prospect Park",
    "Church Av",
    "Newkirk Plaza",
    "Kings Hwy",
    "Sheepshead Bay",
    "Brighton Beach",
};
const uint8_t stops_B_count = 37;

// Route C (40 stops)
const char *const stops_C[] = {
    "168 St",
    "163 St-Amsterdam Av",
    "155 St",
    "145 St",
    "135 St",
    "125 St",
    "116 St",
    "Cathedral Pkwy (110 St)",
    "103 St",
    "96 St",
    "86 St",
    "81 St-Museum of Natural History",
    "72 St",
    "59 St-Columbus Circle",
    "50 St",
    "42 St-Port Authority Bus Terminal",
    "34 St-Penn Station",
    "23 St",
    "14 St",
    "W 4 St-Wash Sq",
    "Spring St",
    "Canal St",
    "Chambers St",
    "Fulton St",
    "High St",
    "Jay St-MetroTech",
    "Hoyt-Schermerhorn Sts",
    "Lafayette Av",
    "Clinton-Washington Avs",
    "Franklin Av",
    "Nostrand Av",
    "Kingston-Throop Avs",
    "Utica Av",
    "Ralph Av",
    "Rockaway Av",
    "Broadway Junction",
    "Liberty Av",
    "Van Siclen Av",
    "Shepherd Av",
    "Euclid Av",
};
const uint8_t stops_C_count = 40;

// Route D (41 stops)
const char *const stops_D[] = {
    "Norwood-205 St",
    "Bedford Park Blvd",
    "Kingsbridge Rd",
    "Fordham Rd",
    "182-183 Sts",
    "Tremont Av",
    "174-175 Sts",
    "170 St",
    "167 St",
    "161 St-Yankee Stadium",
    "155 St",
    "145 St",
    "125 St",
    "59 St-Columbus Circle",
    "7 Av",
    "47-50 Sts-Rockefeller Ctr",
    "42 St-Bryant Pk",
    "34 St-Herald Sq",
    "W 4 St-Wash Sq",
    "Broadway-Lafayette St",
    "Grand St",
    "DeKalb Av",
    "Atlantic Av-Barclays Ctr",
    "Union St",
    "4 Av-9 St",
    "Prospect Av",
    "25 St",
    "36 St",
    "9 Av",
    "Fort Hamilton Pkwy",
    "50 St",
    "55 St",
    "62 St",
    "71 St",
    "79 St",
    "18 Av",
    "20 Av",
    "Bay Pkwy",
    "25 Av",
    "Bay 50 St",
    "Coney Island-Stillwell Av",
};
const uint8_t stops_D_count = 41;

// Route E (32 stops)
const char *const stops_E[] = {
    "Jamaica Center-Parsons/Archer",
    "Sutphin Blvd-Archer Av-JFK Airport",
    "Jamaica-Van Wyck",
    "Briarwood",
    "Kew Gardens-Union Tpke",
    "75 Av",
    "Forest Hills-71 Av",
    "67 Av",
    "63 Dr-Rego Park",
    "Woodhaven Blvd",
    "Grand Av-Newtown",
    "Elmhurst Av",
    "Jackson Hts-Roosevelt Av",
    "65 St",
    "Northern Blvd",
    "46 St",
    "Steinway St",
    "36 St",
    "Queens Plaza",
    "Court Sq-23 St",
    "Lexington Av/53 St",
    "5 Av/53 St",
    "7 Av",
    "50 St",
    "42 St-Port Authority Bus Terminal",
    "34 St-Penn Station",
    "23 St",
    "14 St",
    "W 4 St-Wash Sq",
    "Spring St",
    "Canal St",
    "World Trade Center",
};
const uint8_t stops_E_count = 32;

// Route F (55 stops)
const char *const stops_F[] = {
    "Jamaica-179 St",
    "169 St",
    "Parsons Blvd",
    "Sutphin Blvd",
    "Briarwood",
    "Kew Gardens-Union Tpke",
    "75 Av",
    "Forest Hills-71 Av",
    "67 Av",
    "63 Dr-Rego Park",
    "Woodhaven Blvd",
    "Grand Av-Newtown",
    "Elmhurst Av",
    "Jackson Hts-Roosevelt Av",
    "65 St",
    "Northern Blvd",
    "46 St",
    "Steinway St",
    "36 St",
    "21 St-Queensbridge",
    "Roosevelt Island",
    "Lexington Av/63 St",
    "57 St",
    "47-50 Sts-Rockefeller Ctr",
    "42 St-Bryant Pk",
    "34 St-Herald Sq",
    "23 St",
    "14 St",
    "W 4 St-Wash Sq",
    "Broadway-Lafayette St",
    "2 Av",
    "Delancey St-Essex St",
    "East Broadway",
    "York St",
    "Jay St-MetroTech",
    "Bergen St",
    "Carroll St",
    "Smith-9 Sts",
    "4 Av-9 St",
    "7 Av",
    "15 St-Prospect Park",
    "Fort Hamilton Pkwy",
    "Church Av",
    "Ditmas Av",
    "18 Av",
    "Avenue I",
    "Bay Pkwy",
    "Avenue N",
    "Avenue P",
    "Kings Hwy",
    "Avenue U",
    "Avenue X",
    "Neptune Av",
    "W 8 St-NY Aquarium",
    "Coney Island-Stillwell Av",
};
const uint8_t stops_F_count = 55;

// Route FS (4 stops)
const char *const stops_FS[] = {
    "Franklin Av",
    "Park Pl",
    "Botanic Garden",
    "Prospect Park",
};
const uint8_t stops_FS_count = 4;

// Route FX (39 stops)
const char *const stops_FX[] = {
    "Coney Island-Stillwell Av",
    "W 8 St-NY Aquarium",
    "Neptune Av",
    "Avenue X",
    "Avenue U",
    "Kings Hwy",
    "Avenue P",
    "Avenue N",
    "Bay Pkwy",
    "Avenue I",
    "18 Av",
    "Ditmas Av",
    "Church Av",
    "7 Av",
    "Jay St-MetroTech",
    "York St",
    "East Broadway",
    "Delancey St-Essex St",
    "2 Av",
    "Broadway-Lafayette St",
    "W 4 St-Wash Sq",
    "14 St",
    "23 St",
    "34 St-Herald Sq",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "5 Av/53 St",
    "Lexington Av/53 St",
    "Court Sq-23 St",
    "Queens Plaza",
    "Jackson Hts-Roosevelt Av",
    "Forest Hills-71 Av",
    "75 Av",
    "Kew Gardens-Union Tpke",
    "Briarwood",
    "Sutphin Blvd",
    "Parsons Blvd",
    "169 St",
    "Jamaica-179 St",
};
const uint8_t stops_FX_count = 39;

// Route G (21 stops)
const char *const stops_G[] = {
    "Court Sq",
    "21 St",
    "Greenpoint Av",
    "Nassau Av",
    "Metropolitan Av",
    "Broadway",
    "Flushing Av",
    "Myrtle-Willoughby Avs",
    "Bedford-Nostrand Avs",
    "Classon Av",
    "Clinton-Washington Avs",
    "Fulton St",
    "Hoyt-Schermerhorn Sts",
    "Bergen St",
    "Carroll St",
    "Smith-9 Sts",
    "4 Av-9 St",
    "7 Av",
    "15 St-Prospect Park",
    "Fort Hamilton Pkwy",
    "Church Av",
};
const uint8_t stops_G_count = 21;

// Route GS (2 stops)
const char *const stops_GS[] = {
    "Grand Central-42 St",
    "Times Sq-42 St",
};
const uint8_t stops_GS_count = 2;

// Route H (5 stops)
const char *const stops_H[] = {
    "Broad Channel",
    "Beach 90 St",
    "Beach 98 St",
    "Beach 105 St",
    "Rockaway Park-Beach 116 St",
};
const uint8_t stops_H_count = 5;

// Route J (30 stops)
const char *const stops_J[] = {
    "Jamaica Center-Parsons/Archer",
    "Sutphin Blvd-Archer Av-JFK Airport",
    "121 St",
    "111 St",
    "104 St",
    "Woodhaven Blvd",
    "85 St-Forest Pkwy",
    "75 St-Elderts Ln",
    "Cypress Hills",
    "Crescent St",
    "Norwood Av",
    "Cleveland St",
    "Van Siclen Av",
    "Alabama Av",
    "Broadway Junction",
    "Chauncey St",
    "Halsey St",
    "Gates Av",
    "Kosciuszko St",
    "Myrtle Av",
    "Flushing Av",
    "Lorimer St",
    "Hewes St",
    "Marcy Av",
    "Delancey St-Essex St",
    "Bowery",
    "Canal St",
    "Chambers St",
    "Fulton St",
    "Broad St",
};
const uint8_t stops_J_count = 30;

// Route L (24 stops)
const char *const stops_L[] = {
    "Canarsie-Rockaway Pkwy",
    "East 105 St",
    "New Lots Av",
    "Livonia Av",
    "Sutter Av",
    "Atlantic Av",
    "Broadway Junction",
    "Bushwick Av-Aberdeen St",
    "Wilson Av",
    "Halsey St",
    "Myrtle-Wyckoff Avs",
    "DeKalb Av",
    "Jefferson St",
    "Morgan Av",
    "Montrose Av",
    "Grand St",
    "Graham Av",
    "Lorimer St",
    "Bedford Av",
    "1 Av",
    "3 Av",
    "14 St-Union Sq",
    "6 Av",
    "8 Av",
};
const uint8_t stops_L_count = 24;

// Route M (36 stops)
const char *const stops_M[] = {
    "Forest Hills-71 Av",
    "67 Av",
    "63 Dr-Rego Park",
    "Woodhaven Blvd",
    "Grand Av-Newtown",
    "Elmhurst Av",
    "Jackson Hts-Roosevelt Av",
    "65 St",
    "Northern Blvd",
    "46 St",
    "Steinway St",
    "36 St",
    "21 St-Queensbridge",
    "Roosevelt Island",
    "Lexington Av/63 St",
    "57 St",
    "47-50 Sts-Rockefeller Ctr",
    "42 St-Bryant Pk",
    "34 St-Herald Sq",
    "23 St",
    "14 St",
    "W 4 St-Wash Sq",
    "Broadway-Lafayette St",
    "Delancey St-Essex St",
    "Marcy Av",
    "Hewes St",
    "Lorimer St",
    "Flushing Av",
    "Myrtle Av",
    "Central Av",
    "Knickerbocker Av",
    "Myrtle-Wyckoff Avs",
    "Seneca Av",
    "Forest Av",
    "Fresh Pond Rd",
    "Middle Village-Metropolitan Av",
};
const uint8_t stops_M_count = 36;

// Route N (45 stops)
const char *const stops_N[] = {
    "Astoria-Ditmars Blvd",
    "Astoria Blvd",
    "30 Av",
    "Broadway",
    "36 Av",
    "39 Av-Dutch Kills",
    "Queensboro Plaza",
    "Lexington Av/59 St",
    "5 Av/59 St",
    "57 St-7 Av",
    "49 St",
    "Times Sq-42 St",
    "34 St-Herald Sq",
    "28 St",
    "23 St",
    "14 St-Union Sq",
    "8 St-NYU",
    "Prince St",
    "Canal St",
    "City Hall",
    "Cortlandt St",
    "Rector St",
    "Whitehall St-South Ferry",
    "Court St",
    "Jay St-MetroTech",
    "DeKalb Av",
    "Atlantic Av-Barclays Ctr",
    "Union St",
    "4 Av-9 St",
    "Prospect Av",
    "25 St",
    "36 St",
    "45 St",
    "53 St",
    "59 St",
    "8 Av",
    "Fort Hamilton Pkwy",
    "New Utrecht Av",
    "18 Av",
    "20 Av",
    "Bay Pkwy",
    "Kings Hwy",
    "Avenue U",
    "86 St",
    "Coney Island-Stillwell Av",
};
const uint8_t stops_N_count = 45;

// Route Q (34 stops)
const char *const stops_Q[] = {
    "96 St",
    "86 St",
    "72 St",
    "Lexington Av/63 St",
    "57 St-7 Av",
    "49 St",
    "Times Sq-42 St",
    "34 St-Herald Sq",
    "28 St",
    "23 St",
    "14 St-Union Sq",
    "8 St-NYU",
    "Prince St",
    "Canal St",
    "DeKalb Av",
    "Atlantic Av-Barclays Ctr",
    "7 Av",
    "Prospect Park",
    "Parkside Av",
    "Church Av",
    "Beverley Rd",
    "Cortelyou Rd",
    "Newkirk Plaza",
    "Avenue H",
    "Avenue J",
    "Avenue M",
    "Kings Hwy",
    "Avenue U",
    "Neck Rd",
    "Sheepshead Bay",
    "Brighton Beach",
    "Ocean Pkwy",
    "W 8 St-NY Aquarium",
    "Coney Island-Stillwell Av",
};
const uint8_t stops_Q_count = 34;

// Route R (45 stops)
const char *const stops_R[] = {
    "Forest Hills-71 Av",
    "67 Av",
    "63 Dr-Rego Park",
    "Woodhaven Blvd",
    "Grand Av-Newtown",
    "Elmhurst Av",
    "Jackson Hts-Roosevelt Av",
    "65 St",
    "Northern Blvd",
    "46 St",
    "Steinway St",
    "36 St",
    "Queens Plaza",
    "Lexington Av/59 St",
    "5 Av/59 St",
    "57 St-7 Av",
    "49 St",
    "Times Sq-42 St",
    "34 St-Herald Sq",
    "28 St",
    "23 St",
    "14 St-Union Sq",
    "8 St-NYU",
    "Prince St",
    "Canal St",
    "City Hall",
    "Cortlandt St",
    "Rector St",
    "Whitehall St-South Ferry",
    "Court St",
    "Jay St-MetroTech",
    "DeKalb Av",
    "Atlantic Av-Barclays Ctr",
    "Union St",
    "4 Av-9 St",
    "Prospect Av",
    "25 St",
    "36 St",
    "45 St",
    "53 St",
    "59 St",
    "Bay Ridge Av",
    "77 St",
    "86 St",
    "Bay Ridge-95 St",
};
const uint8_t stops_R_count = 45;

// Route SI (21 stops)
const char *const stops_SI[] = {
    "St George",    "Tompkinsville",   "Stapleton",       "Clifton",
    "Grasmere",     "Old Town",        "Dongan Hills",    "Jefferson Av",
    "Grant City",   "New Dorp",        "Oakwood Heights", "Bay Terrace",
    "Great Kills",  "Eltingville",     "Annadale",        "Huguenot",
    "Prince's Bay", "Pleasant Plains", "Richmond Valley", "Arthur Kill",
    "Tottenville",
};
const uint8_t stops_SI_count = 21;

// Route W (44 stops)
const char *const stops_W[] = {
    "86 St",
    "Avenue U",
    "Kings Hwy",
    "Bay Pkwy",
    "20 Av",
    "18 Av",
    "New Utrecht Av",
    "Fort Hamilton Pkwy",
    "8 Av",
    "59 St",
    "53 St",
    "45 St",
    "36 St",
    "25 St",
    "Prospect Av",
    "4 Av-9 St",
    "Union St",
    "Atlantic Av-Barclays Ctr",
    "DeKalb Av",
    "Jay St-MetroTech",
    "Court St",
    "Whitehall St-South Ferry",
    "Rector St",
    "Cortlandt St",
    "City Hall",
    "Canal St",
    "Prince St",
    "8 St-NYU",
    "14 St-Union Sq",
    "23 St",
    "28 St",
    "34 St-Herald Sq",
    "Times Sq-42 St",
    "49 St",
    "57 St-7 Av",
    "5 Av/59 St",
    "Lexington Av/59 St",
    "Queensboro Plaza",
    "39 Av-Dutch Kills",
    "36 Av",
    "Broadway",
    "30 Av",
    "Astoria Blvd",
    "Astoria-Ditmars Blvd",
};
const uint8_t stops_W_count = 44;

// Route Z (21 stops)
const char *const stops_Z[] = {
    "Jamaica Center-Parsons/Archer",
    "Sutphin Blvd-Archer Av-JFK Airport",
    "121 St",
    "104 St",
    "Woodhaven Blvd",
    "75 St-Elderts Ln",
    "Crescent St",
    "Norwood Av",
    "Van Siclen Av",
    "Alabama Av",
    "Broadway Junction",
    "Chauncey St",
    "Gates Av",
    "Myrtle Av",
    "Marcy Av",
    "Delancey St-Essex St",
    "Bowery",
    "Canal St",
    "Chambers St",
    "Fulton St",
    "Broad St",
};
const uint8_t stops_Z_count = 21;

const subway_route_t subway_routes[] = {
    {"1", stops_line_1, 38},
    {"2", stops_line_2, 61},
    {"3", stops_line_3, 34},
    {"4", stops_line_4, 54},
    {"5", stops_line_5, 39},
    {"6", stops_line_6, 38},
    {"7", stops_line_7, 22},
    {"A", stops_A, 59},
    {"B", stops_B, 37},
    {"C", stops_C, 40},
    {"D", stops_D, 41},
    {"E", stops_E, 32},
    {"F", stops_F, 55},
    {"G", stops_G, 21},
    {"H", stops_H, 5},
    {"J", stops_J, 30},
    {"L", stops_L, 24},
    {"M", stops_M, 36},
    {"N", stops_N, 45},
    {"Q", stops_Q, 34},
    {"R", stops_R, 45},
    {"W", stops_W, 44},
    {"Z", stops_Z, 21},
    {"6X", stops_line_6X, 29},
    {"7X", stops_line_7X, 18},
    {"FS", stops_FS, 4},
    {"FX", stops_FX, 39},
    {"GS", stops_GS, 2},
    {"SI", stops_SI, 21},
};
const uint8_t subway_route_count = 29;
